name: My-Actions

on: push

jobs:
  buildAndRun:
    name: Lint code base
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 15.x ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: npm i
        run: make install

      - name: Linting code
        run: make lint

      - name: Run tests
        run: make test

      - name: Test & publish code coverage
        # https://github.com/paambaati/codeclimate-action
        uses: paambaati/codeclimate-action@v2.7.4
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CODECOVERAGE }}
        with:
          coverageCommand: make test-coverage
          debug: true